default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: dic_day08_development

test:
  <<: *default
  database: dic_day08_test

production:
  <<: *default
  database: dic_day08_production
  username: dic_day08
  password: <%= ENV['DIC_DAY08_DATABASE_PASSWORD'] %>
