# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4d29e063182fb31cf3b7eea76622b7174899120f36c610aa62dcf11b9b41084234fc3b77a4d57a1a4e3319f855929fc1ac0ede7eb700f3630ceb4f009f06eea

test:
  secret_key_base: 2c4de0d3f8dd3e63809853b1eb86294f722f32c8b59914b50079b8ede8101b545e4000532375bab0b734a737c3455bb22d4c7c47755595e74094ca09f1d1ad33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
